dist: trusty
sudo: required
addons:
  apt:
    packages:
      - socat
os:
  - linux
  - osx
language: d
d:
  - ldc
  - ldc-beta
  - ldc-1.8.0
  - dmd
  - dmd-nightly
  - dmd-2.079.1
  - dmd-2.078.3
#script: make -f .travis.mak DC=${DC}
script: 
  - dub test --compiler=${DC} --build=unittest-cov
  - dub run :realtest --compiler=${DC} --build=unittest-cov
after_success:
  - bash <(curl -s https://codecov.io/bash)
